#!/data/data/com.termux/files/usr/bin/bash

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

# get free memory
IFS=" " read USED AVAIL TOTAL <<<$(free -htm | grep "Mem" | awk {'print $3,$7,$2'})
# get processes
PROCESS=$(ps -eo user=|sort|uniq -c | awk '{ print $2 " " $1 }')
PROCESS_ALL=$(echo "$PROCESS"| awk {'print $2'} | awk '{ SUM += $1} END { print SUM }')
PROCESS_ROOT=$(echo "su -c ${PROCESS}"| grep root | awk {'print $2'})
PROCESS_USER=$(echo "$PROCESS"| grep -v root | awk {'print $2'} | awk '{ SUM += $1} END { print SUM }')
# get processors
PROCESSOR_NAME=$(grep "Processor" /proc/cpuinfo | cut -d ' ' -f2- | awk {'print $0'} | head -1)
PROCESSOR_COUNT=$(grep -oP 'processor\t:' /proc/cpuinfo | wc -l)

if [[ -d /system/app/ && -d /system/priv-app ]]; then
    DISTRO="Android $(getprop ro.build.version.release)"
    MODEL="$(getprop ro.product.brand) $(getprop ro.product.model)"
fi

W="\e[0;39m"
G="\e[1;32m"
B="\e[1;34m"
BOLD='\033[1m'

echo -e "
${W}${BOLD}System Info:
$B  Distro    : $W$DISTRO
$B  Host      : $W$MODEL
$B  Kernel    : $W$(uname -sr)

$B  CPU       : $W$PROCESSOR_NAME ($G$PROCESSOR_COUNT$W vCPU)
$B  Processes : $G$PROCESS_USER$W (user), $G$PROCESS_ALL$W (total)
$B  Memory    : $G$USED$W used, $G$AVAIL$W avail, $G$TOTAL$W total$W"
